# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b7f1677fcd0a0577ddaae2a5393dd80cfdea7c813e4c38ce533723083dfbffd5fc8ab07e22b3815487a4eab5fab9610d8bd73a4900d8281ececc93c9c80b7a9

test:
  secret_key_base: b12e7e66433ca8e27323a407bbccbebb3f2c5884630dd81c9fc1f687ce73c27af057a1b951729e01a25b7721fb0c42ae31dc487b372ff79e037fdf03ec06fb50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
